Aggregation
qgrid/ng pull request #132
Opened 2017-02-17 13:54 UTC by mkoty

2017-02-17 14:00 UTC, klumba12 commented on demo/pages/aggregation/index.html
> +		<q-grid:column key="contact.region" aggregation="avg" distinct="true"></q-grid:column>
My suggest is to have something like that
```html
<q-grid:column aggregation="avg" aggregation-options="{distinct: true, serparator: '; '}"
```

2017-02-17 14:10 UTC, mkoty commented on demo/pages/aggregation/index.html
> +		<q-grid:column key="contact.region" aggregation="avg" distinct="true"></q-grid:column>
Maybe if no options just: <q-grid:column aggregation="avg"
If with options, then: <q-grid:column aggregation="type: avg, distinct: true, serparator: '; '}"
?

2017-02-20 10:09 UTC, klumba12 commented on demo/pages/aggregation/index.html
> +		<q-grid:column key="contact.region" aggregation="{type: 'avg', 'distinct': true}" ></q-grid:column>
can we have aggreation ang aggregation-options as separate fields?
90% of aggregations will be simple cases, and we'are triing to have the same type for the model props

2017-02-20 10:09 UTC, klumba12 commented on src/core/column-type/data.column.model.js
> +		this.distinct = false;
should be aggregationOptions = {}

2017-02-20 10:09 UTC, klumba12 commented on src/core/foot/foot.view.js
> +			}
avoid to use eval

2017-02-20 10:09 UTC, klumba12 commented on src/core/services/aggregation.js
> +	static sum(rows, getValue, distinct, separator, avgSet) {
can we just pass here options as 3rd arg, please

2017-02-21 13:54 UTC, klumba12 commented on src/core/services/aggregation.js
> +	static sum(rows, getValue, aggregationOptions, externalSet) {
Rename to just options

2017-02-21 13:54 UTC, klumba12 commented on src/core/services/aggregation.js
> +			let uniqueValues = new Set(),
Can we have one method that will return uniq values?

2017-02-21 13:54 UTC, klumba12 commented on src/core/services/aggregation.js
> +	static sum(rows, getValue, aggregationOptions, externalSet) {
What is external set?

2017-02-21 14:15 UTC, mkoty commented on src/core/services/aggregation.js
> +			let uniqueValues = new Set(),
Yes, we can. But it'll works slowly, because on calculating sum, or getting join, we will walk through array twice.

2017-02-21 14:16 UTC, mkoty commented on src/core/services/aggregation.js
> +	static sum(rows, getValue, aggregationOptions, externalSet) {
This is the Set for filling from another method. I use it in AVG for dividing sum on it's length

2017-02-21 15:39 UTC, etokareva reviewed
Can you also fill in aggregation.md documentation?

2017-02-21 16:19 UTC, etokareva commented on docs/aggregation.md
>  ```javascript
Can user manage aggregations from js?

2017-03-06 13:38 UTC, klumba12 approved these changes

2017-03-06 13:38 UTC, klumba12 commented on demo/data/people/10.json
>  [{"name":{"first":"Lue","last":"Laserna"},"gender":"female","birthday":"1983-09-18","contact":{"address":{"street":"19 Deer Loop","zip":"90732","city":"San Pedro","state":"CA"},"email":["lue.laserna@
Put it under pages

2017-03-06 14:17 UTC, etokareva requested changes
I think this documentation is not full

2017-03-07 08:41 UTC, klumba12 requested changes

2017-03-07 08:41 UTC, klumba12 commented on src/core/foot/foot.view.js
> +			let aggregation = column.aggregation,
should be const,
each line should contains modifier e,g,
const aggregation = ;
const aggregationOptions = ;

2017-03-07 08:41 UTC, klumba12 commented on src/core/services/aggregation.js
> +	static avg(rows, getValue, aggregationOptions) {
rename aggregationOptions to options everywhere

2017-03-07 08:41 UTC, klumba12 commented on src/core/services/aggregation.js
>  			i = 0,
each variable should has let

2017-03-07 08:41 UTC, klumba12 commented on src/ng/components/column/column.js
> +			$parse = this.$parse,
each line with const

2017-03-07 08:41 UTC, klumba12 commented on src/ng/components/column/column.js
> +		$attrs.aggregationOptions = $parse($attrs.aggregationOptions)(this);
this should be in copy method

2017-03-07 08:41 UTC, klumba12 commented on src/core/foot/foot.view.js
> +			return Aggregation[aggregation](rows, getValue, aggregationOptions || {});
here should be default value not {}

2017-03-07 15:01 UTC, klumba12 approved these changes

2017-03-07 15:04 UTC, etokareva approved these changes

2017-03-07 15:04 UTC, merged